### ISSUE TITLE
The version in the doc mismatches the actual release

### ISSUE THREAD

**Issue by angerhang** [tianhaoz95/mirror-action#8]
Hi Tianhao, thanks for your work on this snippet. 

I was using your API to compare two files today but I encountered the following issue:
```
Error: An action could not be found at the URI 'https://api.github.com/repos/tianhaoz95/mirror-action/tarball/v1'
```

Would you advise on what to do here?

**Comment by tianhaoz95** [comment]
Ah I see, my bad. so I released v1.01 instead of v1 per https://github.com/marketplace/actions/mirror-action

you can use:

```yml
- name: Mirror Action
  uses: tianhaoz95/mirror-action@v1.0.1
```

@angerhang

**Comment by tianhaoz95** [comment]
If that works for you, could you update the doc if you have time?

I am working all nighters to catch a project deadline :(

![I'm fine](https://media.giphy.com/media/eIfYQTaK3148kmMCxT/giphy-downsized.gif)

**Comment by tianhaoz95** [comment]
Also, thanks for reporting the issue!

@all-contributors please add angerhang for bug

**Comment by angerhang** [comment]
> If that works for you, could you update the doc if you have time?
> 
> I am working all nighters to catch a project deadline :(
> 
> ![I'm fine](https://camo.githubusercontent.com/9ef0ceef575eb7b60f22c63b51294f1facfa6c02/68747470733a2f2f6d656469612e67697068792e636f6d2f6d656469612f654966595154614b333134386b6d4d4378542f67697068792d646f776e73697a65642e676966)

Sure, let me test it out :D

**Comment by angerhang** [comment]
Yap it works :D 

Thanks for the quick response.

You can close this issue when the PR is merged.

**Comment by tianhaoz95** [comment]
Thanks!

**Comment by tianhaoz95** [comment]
@all-contributors please add angerhang for doc
